### ISSUE TITLE
Open3D GUI / visualization tools not enabled

### ISSUE THREAD

**Issue by HernandoR** [conda-forge/open3d-feedstock#20]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

The following command brokes:
```
conda create -n open3d open3d
conda activate open3d
open3d draw
```

```
***************************************************
* Open3D: A Modern Library for 3D Data Processing *
*                                                 *
* Version 0.18.0+bff1dd2                          *
* Docs    https://www.open3d.org/docs             *
* Code    https://github.com/isl-org/Open3D       *
***************************************************
usage: open3d draw [-h] [filename]

Load and visualize a 3D model. Example usage:
  open3d draw                                            # Start a blank Open3D viewer
  open3d draw path/to/model_file                         # Visualize a 3D model file

positional arguments:
  filename    Name of the mesh or point cloud file.

options:
  -h, --help  Show this help message and exit.
Traceback (most recent call last):
  File "/home/lz/miniforge3/envs/open3d/bin/open3d", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lz/miniforge3/envs/open3d/lib/python3.11/site-packages/open3d/tools/cli.py", line 368, in main
    return args.func(subparsers.choices[args.command], args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lz/miniforge3/envs/open3d/lib/python3.11/site-packages/open3d/tools/cli.py", line 200, in _draw
    app.main()
  File "/home/lz/miniforge3/envs/open3d/lib/python3.11/site-packages/open3d/app.py", line 18, in main
    o3d.visualization.app.run_viewer(args)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'open3d.visualization' has no attribute 'app'
```

error remains for python 3.11 and 3.13

### Installed packages

```shell
# packages in environment at /home/lz/miniforge3/envs/open3d:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohappyeyeballs          2.4.4              pyhd8ed1ab_1    conda-forge
aiohttp                   3.11.11         py311h2dc5d0c_0    conda-forge
aiosignal                 1.3.2              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.13               hb9d3cd8_0    conda-forge
assimp                    5.4.3                h8943939_0    conda-forge
attrs                     24.3.0             pyh71513ae_0    conda-forge
blinker                   1.9.0              pyhff2d567_0    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
brotli-python             1.1.0           py311hfdbb021_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.4               hb9d3cd8_0    conda-forge
ca-certificates           2024.12.14           hbcca054_0    conda-forge
cairo                     1.18.2               h3394656_1    conda-forge
certifi                   2024.12.14         pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py311hf29c0ef_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_1    conda-forge
click                     8.1.8              pyh707e725_0    conda-forge
cudatoolkit               11.8.0              h4ba93d1_13    conda-forge
cyrus-sasl                2.1.27               h54b06d7_7    conda-forge
dash                      2.18.2             pyhd8ed1ab_1    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
double-conversion         3.3.0                h59595ed_0    conda-forge
embree                    4.3.3                h3173236_0    conda-forge
expat                     2.6.4                h5888daf_0    conda-forge
flask                     3.1.0              pyhff2d567_0    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h7e30c49_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
frozenlist                1.5.0           py311h9ecbd09_0    conda-forge
gl2ps                     1.4.2                hae5d5c5_1    conda-forge
glew                      2.1.0                h9c3ff4c_2    conda-forge
glfw                      3.4                  hd590300_0    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
h2                        4.1.0              pyhd8ed1ab_1    conda-forge
harfbuzz                  9.0.0                hda332d3_1    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.4          nompi_h2d575fe_105    conda-forge
hpack                     4.0.0              pyhd8ed1ab_1    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_1    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
importlib-metadata        8.5.0              pyha770c72_1    conda-forge
itsdangerous              2.2.0              pyhd8ed1ab_1    conda-forge
jinja2                    3.1.5              pyhd8ed1ab_0    conda-forge
jsoncpp                   1.9.6                hf42df4d_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libblas                   3.9.0           26_linux64_openblas    conda-forge
libboost                  1.86.0               h6c02f8c_3    conda-forge
libcblas                  3.9.0           26_linux64_openblas    conda-forge
libclang-cpp19.1          19.1.6          default_hb5137d0_0    conda-forge
libclang13                19.1.6          default_h9c6a7e4_0    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.11.1               h332b0f4_0    conda-forge
libdeflate                1.23                 h4ddbbb0_0    conda-forge
libdrm                    2.4.124              hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libegl                    1.7.0                ha4b6fd6_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgl                     1.7.0                ha4b6fd6_2    conda-forge
libglib                   2.82.2               h2ff4ddf_0    conda-forge
libglu                    9.0.3                h03adeef_0    conda-forge
libglvnd                  1.7.0                ha4b6fd6_2    conda-forge
libglx                    1.7.0                ha4b6fd6_2    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libhwloc                  2.11.2          default_h0d58e46_1001    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           26_linux64_openblas    conda-forge
liblapacke                3.9.0           26_linux64_openblas    conda-forge
libllvm19                 19.1.6               ha7bfdaf_0    conda-forge
liblzf                    3.6                  hb9d3cd8_3    conda-forge
liblzma                   5.6.3                hb9d3cd8_1    conda-forge
libmpdec                  4.0.0                h4bc722e_0    conda-forge
libnetcdf                 4.9.2           nompi_h5ddbaa4_116    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libntlm                   1.8                  hb9d3cd8_0    conda-forge
libogg                    1.3.5                h4ab18f5_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_1    conda-forge
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libpq                     17.2                 h3b95a9b_1    conda-forge
libsodium                 1.0.20               h4ab18f5_0    conda-forge
libsqlite                 3.47.2               hee588c1_0    conda-forge
libssh2                   1.11.1               hf672d98_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtheora                 1.1.1             h4ab18f5_1006    conda-forge
libtiff                   4.7.0                hd9ff511_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.5.0                h851e524_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h2c5496b_1    conda-forge
libxml2                   2.13.5               h8d12d68_1    conda-forge
libzip                    1.11.2               h6991a6a_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
loguru                    0.7.2           py311h38be061_2    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markupsafe                3.0.2           py311h2dc5d0c_1    conda-forge
msgpack-python            1.1.0           py311hd18a35c_0    conda-forge
multidict                 6.1.0           py311h2dc5d0c_2    conda-forge
mysql-common              9.0.1                h266115a_3    conda-forge
mysql-libs                9.0.1                he0572af_3    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_1    conda-forge
nlohmann_json             3.11.3               he02047a_1    conda-forge
numpy                     2.2.1           py311hf916aec_0    conda-forge
open3d                    0.18.0          py311hc82502a_14    conda-forge
openldap                  2.6.9                he970967_0    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
packaging                 24.2               pyhd8ed1ab_2    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pip                       24.3.1             pyh8b19718_2    conda-forge
pixman                    0.44.2               h29eaf8c_0    conda-forge
plotly                    5.24.1             pyhd8ed1ab_1    conda-forge
proj                      9.5.1                h0054346_0    conda-forge
propcache                 0.2.1           py311h9ecbd09_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pugixml                   1.14                 h59595ed_0    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pysocks                   1.7.1              pyha55dd90_7    conda-forge
python                    3.11.11         h9e4cc4f_1_cpython    conda-forge
python_abi                3.11                    5_cp311    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
qt6-main                  6.7.3                h6e8976b_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_1    conda-forge
retrying                  1.3.3              pyhd8ed1ab_3    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
six                       1.17.0             pyhd8ed1ab_0    conda-forge
snappy                    1.2.1                h8bd8927_1    conda-forge
sqlite                    3.47.2               h9eae976_0    conda-forge
tbb                       2022.0.0             hceb3a55_0    conda-forge
tenacity                  9.0.0              pyhd8ed1ab_1    conda-forge
tinyobjloader             1.0.7                h59595ed_2    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing-extensions         4.12.2               hd8ed1ab_1    conda-forge
typing_extensions         4.12.2             pyha770c72_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
urllib3                   2.3.0              pyhd8ed1ab_0    conda-forge
utfcpp                    4.0.6                h005c6e1_0    conda-forge
vtk-base                  9.3.1           qt_py311h875efc5_212    conda-forge
wayland                   1.23.1               h3e06ad9_0    conda-forge
werkzeug                  3.1.3              pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
wslink                    2.2.1              pyhd8ed1ab_1    conda-forge
xcb-util                  0.4.1                hb711507_2    conda-forge
xcb-util-cursor           0.1.5                hb9d3cd8_0    conda-forge
xcb-util-image            0.4.0                hb711507_2    conda-forge
xcb-util-keysyms          0.4.1                hb711507_0    conda-forge
xcb-util-renderutil       0.3.10               hb711507_0    conda-forge
xcb-util-wm               0.4.2                hb711507_0    conda-forge
xkeyboard-config          2.43                 hb9d3cd8_0    conda-forge
xorg-libice               1.1.2                hb9d3cd8_0    conda-forge
xorg-libsm                1.2.5                he73a12e_0    conda-forge
xorg-libx11               1.8.10               h4f16b4b_1    conda-forge
xorg-libxau               1.0.12               hb9d3cd8_0    conda-forge
xorg-libxcomposite        0.4.6                hb9d3cd8_2    conda-forge
xorg-libxcursor           1.2.3                hb9d3cd8_0    conda-forge
xorg-libxdamage           1.1.6                hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxfixes            6.0.1                hb9d3cd8_0    conda-forge
xorg-libxi                1.8.2                hb9d3cd8_0    conda-forge
xorg-libxinerama          1.1.5                h5888daf_1    conda-forge
xorg-libxrandr            1.5.4                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.12               hb9d3cd8_0    conda-forge
xorg-libxt                1.3.1                hb9d3cd8_0    conda-forge
xorg-libxtst              1.2.5                hb9d3cd8_3    conda-forge
xorg-libxxf86vm           1.1.6                hb9d3cd8_0    conda-forge
yarl                      1.18.3          py311h9ecbd09_0    conda-forge
zeromq                    4.3.5                h3b0a872_7    conda-forge
zipp                      3.21.0             pyhd8ed1ab_1    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstandard                 0.23.0          py311hbc35293_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
active environment : open3d
    active env location : /home/lz/miniforge3/envs/open3d
            shell level : 4
       user config file : /home/lz/.condarc
 populated config files : /home/lz/miniforge3/.condarc
                          /home/lz/.condarc
          conda version : 24.11.2
    conda-build version : not installed
         python version : 3.12.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.11.2=0
                          __cuda=12.6=0
                          __glibc=2.39=0
                          __linux=6.8.0=0
                          __unix=0=0
       base environment : /home/lz/miniforge3  (writable)
      conda av data dir : /home/lz/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
          package cache : /home/lz/miniforge3/pkgs
                          /home/lz/.conda/pkgs
       envs directories : /home/lz/miniforge3/envs
                          /home/lz/.conda/envs
               platform : linux-64
             user-agent : conda/24.11.2 requests/2.32.3 CPython/3.12.6 Linux/6.8.0-51-generic ubuntu/24.04.1 glibc/2.39 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.9
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by Tobias-Fischer** [comment]
Could you please try if this works with an open3d installed via pip?

**Comment by HernandoR** [comment]
Yes, pip installed open3d with python 3.11 works fine

________________________________

**Comment by Tobias-Fischer** [comment]
Fixed in #59
